name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1️⃣ Checkout del repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Instalar Node.js y dependencias
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # 3️⃣ Ejecutar pruebas unitarias
      - name: Run tests
        run: npm test

      # 4️⃣ Build y push Docker a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mi-app:latest

      # 5️⃣ Deploy a Render
      - name: Deploy to Render
        run: |
          echo "Disparando deploy en Render..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}" --fail
